### ISSUE TITLE
Issue streaming SB500 after upgrade to 4.0

### ISSUE THREAD

**Issue by almoney** [GerryDazoo/Slinger#533]
### Discussed in https://github.com/GerryDazoo/Slinger/discussions/532

<div type='discussions-op-text'>

<sup>Originally posted by **almoney** February 13, 2023</sup>
I upgraded my slingers to 4.0 and have an issue streaming from my SB500 only everything else working fine.

This is in the log:

02/13/2023, 17:49:41.608   Streaming request from ('xxxx', 57770)  /ASling/Novi500 
STREAM=xxxx:57770:0
Starting remote stream 2

Slinginfo  "350/500/M1" 15 60 192.168.11.189 5221 3072 3 pw
Novi500 Starting Stream for  x.y.z.a:57770
Novi500 Opening Control stream 0x2000 0 0
Connecting... ('192.168.11.189', 5221) Control
Novi500 Selecting Video Source 1
Novi500 Keycodes= [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 26, 27, 28, 29, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 62, 63, 64]
VideoParameters: Resolution= 15 FrameRate= 60 VideoBandwidth= 8000 VideoSmoothness= 63 IframeRate= 5 AudioBitRate= 96
Connecting... ('192.168.11.189', 5221) Stream
**Traceback (most recent call last):
  File "/home/slingbox/slingbox_server.py", line 836, in streamer
    s_ctl, stream  = start_slingbox_session(streams)
  File "/home/slingbox/slingbox_server.py", line 428, in start_slingbox_session
    first_buffer = bytearray(stream.recv(pksize, socket.MSG_PEEK))
socket.timeout: timed out
Novi500 Badness starting slingbox session  timed out None**
Streamer:  Novi500 Waiting for first stream, flushing any IR requests that arrive while not connected to slingbox

Config for this box:

[Novi500]
sbtype="350/500/M1"
password=removed
ipaddress=192.168.11.189
port=5221
Resolution=15
FrameRate=60
AudioBitRate=96
VideoBandwidth=8000
VideoSmoothness=63
VideoSource=1
maxstreams=3

Any thoughts?
(works fine after I roll back.)
</div>

**Comment by almoney** [comment]
Using the following allows SMPlayer and Slinger Player to work.  (VLC worked with the previous parameters and 4.0 Slinger server.

VideoParameters: Resolution= 12 FrameRate= 60 VideoBandwidth= 6000 VideoSmoothness= 50 IframeRate= 5 AudioBitRate= 96

**Comment by almoney** [comment]
We can close with the lastest push.  I wanted to document that the issue was source equipment that goes to sleep with no video output. This needed the extra time to start.  We may want to add auto "POWER" command if this occurs.  The old slingplayer client detected this condition and prompted asking to send power on.
