### ISSUE TITLE
Debian upgrade to 12 error

### ISSUE THREAD

**Issue by tom76017** [GerryDazoo/Slinger#605]
I'm getting a encoding error after upgrading to bookworm.

> VideoParameters: Resolution= 16 FrameRate= 30 VideoBandwidth= 1984 VideoSmoothness= 59 IframeRate= 4 AudioBitRate= 64
Connecting... ('192.168.11.70', 5301) Stream
Traceback (most recent call last):
  File "/home/slingbox/slingbox_server.py", line 836, in streamer
    s_ctl, stream  = start_slingbox_session(streams)
  File "/home/slingbox/slingbox_server.py", line 429, in start_slingbox_session
    magic = bytearray(u'Slingbox'.encode('utf-16le'))
LookupError: unknown encoding: utf-16le
Slingbox-M1 Badness starting slingbox session  unknown encoding: utf-16le None

**Comment by tom76017** [comment]
Found my error.  Python was upgraded to python3.11.  I had hard coded python3.9 in my service.
