### ISSUE TITLE
OSError: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by Deltapie7** [GerryDazoo/Slinger#8]
Had it working, ran into an error, decided to start over, now have the following error. Thoughts?

Python 3.5.3 (/usr/bin/python3)
>>> %Run slingbox_server.py
Version : 1.01 Running on Linux-4.19.66-v7+-armv7l-with-debian-9.13
Connection Manager Running 10 max streams....
Streamer Running: 
starting up on  port 8080
Checking  ('192.168.86.172', 5222)
Using slingbox at  ('192.168.86.172', 5222)
Streamer: Waiting for first stream, flushing any IR requests that arrive while not connected to slingbox
Traceback (most recent call last):
  File "/home/slingbox/slingbox_server.py", line 818, in <module>
    app.run(host='0.0.0.0', port=9998, debug=False)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 708, in run_simple
    inner()
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 670, in inner
    fd=fd)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 564, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 476, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/usr/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/usr/lib/python3.5/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

From Slingbox
192.168.86.172
Network port
5222

[SLINGBOX]
sbtype=350/500
password=GPgyF9IIGNUUn04
; uncomment the next lines ipaddress and port with your local network info
; if you don't want the server to automatically find your 
; slingbox on the local network. Needed if server and slingbox are
; not on the same LAN segment. ALso removes requirement for the netifaces module  
ipaddress=192.168.86.172
port=5222

; Following are the default values
; Default resolution when server starts
;Resolution=12

; Valid Values 1, 6, 10, 15, 20, 30, 60   depending on resolution
;FrameRate=30

;Min 50 Max 8000
;VideoBandwidth=2000

; Min 0 (auto) max 63
;VideoSmoothness=63

; Send Iframe every n seconds Max 30
;IframeRate=5

; Audio Bit Rate. Valid Options 16, 20, 32, 40, 48, 64, 96 Default 32
;AudioBitRate=32

[SERVER]
; local port number for the server to listen on for connections
port=65432
maxstreams=10
enableremote=yes

**Comment by Deltapie7** [comment]
Was totally my fault and figured it out as soon as I posted this. Sorry
